version: '3'
services:
  backend:
    build: ./be_karem
    ports:
      - "3000:3000"
    volumes:
      - ./be_karem:/app
    environment:
      - NODE_ENV=development
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./fe_karem:/app
    ports:
      - "5173:5173"
    command: sh -c "cd /app && npm install && npm run dev"
