/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as CodeRunnerImport } from './routes/code-runner'
import { Route as AdminPanelImport } from './routes/admin-panel'
import { Route as IndexImport } from './routes/index'
import { Route as ZadaniaIndexImport } from './routes/zadania/index'
import { Route as StrefaNauczycielaIndexImport } from './routes/strefa-nauczyciela/index'
import { Route as ZadaniaIdImport } from './routes/zadania/$id'
import { Route as BlogIdImport } from './routes/blog/$id'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const CodeRunnerRoute = CodeRunnerImport.update({
  id: '/code-runner',
  path: '/code-runner',
  getParentRoute: () => rootRoute,
} as any)

const AdminPanelRoute = AdminPanelImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ZadaniaIndexRoute = ZadaniaIndexImport.update({
  id: '/zadania/',
  path: '/zadania/',
  getParentRoute: () => rootRoute,
} as any)

const StrefaNauczycielaIndexRoute = StrefaNauczycielaIndexImport.update({
  id: '/strefa-nauczyciela/',
  path: '/strefa-nauczyciela/',
  getParentRoute: () => rootRoute,
} as any)

const ZadaniaIdRoute = ZadaniaIdImport.update({
  id: '/zadania/$id',
  path: '/zadania/$id',
  getParentRoute: () => rootRoute,
} as any)

const BlogIdRoute = BlogIdImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelImport
      parentRoute: typeof rootRoute
    }
    '/code-runner': {
      id: '/code-runner'
      path: '/code-runner'
      fullPath: '/code-runner'
      preLoaderRoute: typeof CodeRunnerImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdImport
      parentRoute: typeof rootRoute
    }
    '/zadania/$id': {
      id: '/zadania/$id'
      path: '/zadania/$id'
      fullPath: '/zadania/$id'
      preLoaderRoute: typeof ZadaniaIdImport
      parentRoute: typeof rootRoute
    }
    '/strefa-nauczyciela/': {
      id: '/strefa-nauczyciela/'
      path: '/strefa-nauczyciela'
      fullPath: '/strefa-nauczyciela'
      preLoaderRoute: typeof StrefaNauczycielaIndexImport
      parentRoute: typeof rootRoute
    }
    '/zadania/': {
      id: '/zadania/'
      path: '/zadania'
      fullPath: '/zadania'
      preLoaderRoute: typeof ZadaniaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/code-runner': typeof CodeRunnerRoute
  '/users': typeof UsersRoute
  '/blog/$id': typeof BlogIdRoute
  '/zadania/$id': typeof ZadaniaIdRoute
  '/strefa-nauczyciela': typeof StrefaNauczycielaIndexRoute
  '/zadania': typeof ZadaniaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/code-runner': typeof CodeRunnerRoute
  '/users': typeof UsersRoute
  '/blog/$id': typeof BlogIdRoute
  '/zadania/$id': typeof ZadaniaIdRoute
  '/strefa-nauczyciela': typeof StrefaNauczycielaIndexRoute
  '/zadania': typeof ZadaniaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRoute
  '/code-runner': typeof CodeRunnerRoute
  '/users': typeof UsersRoute
  '/blog/$id': typeof BlogIdRoute
  '/zadania/$id': typeof ZadaniaIdRoute
  '/strefa-nauczyciela/': typeof StrefaNauczycielaIndexRoute
  '/zadania/': typeof ZadaniaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/code-runner'
    | '/users'
    | '/blog/$id'
    | '/zadania/$id'
    | '/strefa-nauczyciela'
    | '/zadania'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-panel'
    | '/code-runner'
    | '/users'
    | '/blog/$id'
    | '/zadania/$id'
    | '/strefa-nauczyciela'
    | '/zadania'
  id:
    | '__root__'
    | '/'
    | '/admin-panel'
    | '/code-runner'
    | '/users'
    | '/blog/$id'
    | '/zadania/$id'
    | '/strefa-nauczyciela/'
    | '/zadania/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanelRoute: typeof AdminPanelRoute
  CodeRunnerRoute: typeof CodeRunnerRoute
  UsersRoute: typeof UsersRoute
  BlogIdRoute: typeof BlogIdRoute
  ZadaniaIdRoute: typeof ZadaniaIdRoute
  StrefaNauczycielaIndexRoute: typeof StrefaNauczycielaIndexRoute
  ZadaniaIndexRoute: typeof ZadaniaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanelRoute: AdminPanelRoute,
  CodeRunnerRoute: CodeRunnerRoute,
  UsersRoute: UsersRoute,
  BlogIdRoute: BlogIdRoute,
  ZadaniaIdRoute: ZadaniaIdRoute,
  StrefaNauczycielaIndexRoute: StrefaNauczycielaIndexRoute,
  ZadaniaIndexRoute: ZadaniaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin-panel",
        "/code-runner",
        "/users",
        "/blog/$id",
        "/zadania/$id",
        "/strefa-nauczyciela/",
        "/zadania/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin-panel": {
      "filePath": "admin-panel.tsx"
    },
    "/code-runner": {
      "filePath": "code-runner.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/blog/$id": {
      "filePath": "blog/$id.tsx"
    },
    "/zadania/$id": {
      "filePath": "zadania/$id.tsx"
    },
    "/strefa-nauczyciela/": {
      "filePath": "strefa-nauczyciela/index.tsx"
    },
    "/zadania/": {
      "filePath": "zadania/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
